---
title: "scoring"
output: github_document
date: '2022-04-13'
---


```{r}
library(scoringRules)
library(tidyverse)
```


```{r}
data <- list.files(path = "./forecasts/",
               pattern = "*.csv", 
               full.names = T) %>% 
        read_csv() 
data <- data[-1]
```

```{r}
library(scoringRules)

# trivial wrapper to score both logs and crps
scores <- function(observed, predicted) {
  logsscore <- scoringRules::logs_sample(observed, predicted)
  crpsscore <- scoringRules::crps_sample(observed, predicted)
  # drops the first point (initial condition)
  data.frame(logs = mean(logsscore[-1]), crps =  mean(crpsscore[-1]))
}
```


```{r}

score_all <- function(data, groups = NULL) {
    
true <- data |> filter(true_model)
fcst <- data |> filter(!true_model)

# key trick is to make forecast a t_max x ensembles matrix for scoringRules:
predicted <- fcst |>
  select(t = time, i = ensemble, value) |> # Not sure if this should be iter here hmm but this might be addressed later
  pivot_wider(id_cols = "t", names_from="i", values_from = "value") |> 
  select(-t) |> 
  as.matrix()

# just select and rename relevant columns
test <- true |>  select(t = time, i = ensemble, value)

# Here we go! score each test timeseries against the entire predicted ensemble!
rep_scores <- 
  test |> 
  group_by(i) |> # group by i? 
  group_map(~ scores(.x$value, predicted)) |> 
  bind_rows()

# add any "grouping variables" on as additional columns for bookkeeping
bind_cols(rep_scores, groups)
}
```



```{r}
# now actually run the scoring over all iterations, ml_models, tp_models:

bench::bench_time({
rep_scores <- data |> 
  group_by(iter, ml_model, tp_model, case) |>
  group_map(~ score_all(.x, .y) ,.keep = TRUE) |> 
  bind_rows()

})
```


```{r}
# Logs Plot
rep_scores %>% 
  filter(case == 10 |  case == 100 | case == 1000) %>% 
  #filter(tp_model == "stochastic") %>% 
  ggplot(aes(ml_model, logs)) + 
  geom_boxplot(outlier.shape = 1) +
  #geom_jitter() + 
  facet_grid(tp_model~case, scales="free")
```

```{r}
# CRPS Plot
rep_scores %>% 
  filter(case == 10 |  case == 100 | case == 1000) %>% 
  #filter(tp_model == "stochastic") %>% 
  ggplot(aes(ml_model, crps)) + 
  geom_boxplot(outlier.shape = 1) +
  #geom_jitter() + 
  facet_grid(tp_model~case, scales="free")
```