hyperparameters = {
    "model" : "LSTM",
    "batch_size" : 32,
    "dropout" : 0.5, 
    "hidden_dim" : 64,
    "n_rnn_layers" : 1,
    "n_epochs" : 200,
    "optimizer_kwargs" : {"lr" : 1.0e-2},
    "model_name" : "test",
    "log_tensorboard" : True,
    "random_state" : 42,
    "input_chunk_length" : 25,
    "output_chunk_length" : 24,
    "force_reset" : True,
    "save_checkpoints" : True,
    "torch_device_str" : "cuda:0",
}
